algoritmo "Saldo"
// Função : Verificar se o saldo é positivo ou negativo
// Autor : Davi Ramos
// Data : 25/05/2023
// Seção de Declarações

var

sal: real
men: real

inicio

escreval ("Qual é o seu salário?")
leia (sal)

escreval ("Qual é o valor gasto por mensalidade")
leia (men)


se (sal<men)entao
   escreval ("Seu saldo é negativo")

senao
   escreval ("Seu saldo é positivo")
  
fimse

fimalgoritmo
