Algoritmo "Intervalo"
// Descrição   : Verifica se o numero digitado está entre 100 e 200
// Autor(a)    : Davi Ramos
// Data atual  : 25/05/2023
Var

num:real

Inicio

escreval("Digite um numero, que irei dizer se ele está entre 100 e 200")
leia(num)

se ((num<200) e (num>100)) entao
   escreval("Este numero etá entre o intervalo de 100 e 200")
   
senao
   escreval("Este numero não etá entre o intervalo de 100 e 200")
   
fimse

Fimalgoritmo
