algoritmo "Dolar"
// Função : Converter dolar em real
// Autor : Davi Ramos
// Data : 23/03/2023
// Seção de Declarações 
var

din,dol,cot,nome:real

inicio

escreval("Digite o valor da cotação do dolar")
leia(cot)

escreval("Quantos dólares voce quer converter em reais")
leia(dol)

din <- dol/cot

escreval("")
escreval("")
escreval(dol," dólares vale", din," reais")

fimalgoritmo
